version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
  redis:
    image: redis:alpine
    ports: ["6379:6379"]
  elasticsearch:
    image: elasticsearch:8.10.2
    environment: ["discovery.type=single-node", "xpack.security.enabled=false"]
    ports: ["9200:9200"]